"""Public API for ReviewKit."""

from reviewkit.anchors import (
    ANCHOR_LAST,
    is_supported_anchor,
    parse_body_anchor_index,
)
from reviewkit.comments import DocxComment, comments_for_locator, read_comments
from reviewkit.context import (
    EmptyReviewContextProvider,
    ReviewContext,
    ReviewContextProvider,
)
from reviewkit.document import ReviewDocument
from reviewkit.finality import (
    ReviewFinalityAssessment,
    ReviewFinalityStatus,
    assess_review_finality,
)
from reviewkit.insertions import (
    SUGGESTION_MARKER_PREFIX,
    InsertionAction,
    InsertionKind,
    contains_suggestion_marker,
    format_suggestion_text,
)
from reviewkit.llm import (
    LLMCapabilities,
    LLMClient,
    LLMClientError,
    LLMClientFailure,
    LLMRequestOptions,
    MockLLMClient,
    StructuredOutputMode,
)
from reviewkit.markup_purity import (
    MarkupReport,
    has_comments,
    has_suggestion_marker,
    has_tracked_revisions,
    inspect_markup,
)
from reviewkit.models import (
    ActionStatus,
    EvidenceRef,
    ReviewAction,
    ReviewActionType,
    ReviewBoundError,
    ReviewDimension,
    ReviewFailureClass,
    ReviewFinding,
    ReviewLocator,
    ReviewReference,
    ReviewResponse,
    ReviewResult,
    ReviewScope,
    ReviewStats,
    RevisionCoverageError,
    RevisionCoverageState,
    RevisionLedger,
    SourceRevision,
    SourceRevisionKind,
    canonical_action_dump,
)
from reviewkit.parser_docx import DocxFootnote, load_docx, read_footnotes
from reviewkit.pipeline import review_document
from reviewkit.policy import ActionPolicy, PolicyGuard
from reviewkit.profile import ActionPolicyConfig, ReviewProfile, load_profile
from reviewkit.renderer_docx import RenderIntegrityError
from reviewkit.review_outcomes import (
    IncorporatedCommentOutcome,
    RenderedActionAssessment,
    ReviewChangeMetrics,
    assess_rendered_actions,
    incorporated_comment_outcomes,
    measure_review_changes,
    read_metadata_marker,
    revision_signatures,
    set_metadata_marker,
    strip_metadata_marker,
)
from reviewkit.revision_rejection import RejectRevisionsError, reject_all_revisions
from reviewkit.revisions import (
    AcceptRevisionsError,
    accept_all_revisions,
    apply_reviewed_markup,
)

__all__ = [
    "ANCHOR_LAST",
    "SUGGESTION_MARKER_PREFIX",
    "AcceptRevisionsError",
    "ActionPolicy",
    "ActionPolicyConfig",
    "ActionStatus",
    "DocxComment",
    "DocxFootnote",
    "EmptyReviewContextProvider",
    "EvidenceRef",
    "IncorporatedCommentOutcome",
    "InsertionAction",
    "InsertionKind",
    "LLMCapabilities",
    "LLMClient",
    "LLMClientError",
    "LLMClientFailure",
    "LLMRequestOptions",
    "MarkupReport",
    "MockLLMClient",
    "PolicyGuard",
    "PortableReviewTrailError",
    "PortableReviewTrailProfile",
    "RejectRevisionsError",
    "RemarkDisposition",
    "RemarkWeight",
    "RenderIntegrityError",
    "RenderedActionAssessment",
    "ReviewAction",
    "ReviewActionType",
    "ReviewArtifactPreservationError",
    "ReviewArtifactPurityAssessment",
    "ReviewBoundError",
    "ReviewChangeMetrics",
    "ReviewContext",
    "ReviewContextProvider",
    "ReviewDimension",
    "ReviewDocument",
    "ReviewFailureClass",
    "ReviewFinalityAssessment",
    "ReviewFinalityStatus",
    "ReviewFinding",
    "ReviewLocator",
    "ReviewProfile",
    "ReviewReference",
    "ReviewRemark",
    "ReviewResponse",
    "ReviewResult",
    "ReviewScope",
    "ReviewStats",
    "RevisionCoverageError",
    "RevisionCoverageState",
    "RevisionLedger",
    "SourceRevision",
    "SourceRevisionKind",
    "StructuredOutputMode",
    "accept_all_revisions",
    "append_portable_review_trail",
    "apply_reviewed_markup",
    "assert_docx_structure_preserved",
    "assess_rendered_actions",
    "assess_review_artifact_purity",
    "assess_review_finality",
    "canonical_action_dump",
    "comments_for_locator",
    "compare_review_remarks",
    "contains_suggestion_marker",
    "format_suggestion_text",
    "has_comments",
    "has_portable_review_trail",
    "has_suggestion_marker",
    "has_tracked_revisions",
    "incorporated_comment_outcomes",
    "inspect_markup",
    "is_supported_anchor",
    "load_docx",
    "load_profile",
    "measure_review_changes",
    "parse_body_anchor_index",
    "read_comments",
    "read_footnotes",
    "read_metadata_marker",
    "reject_all_revisions",
    "remark_disposition",
    "remark_weight",
    "review_document",
    "review_remarks",
    "revision_signatures",
    "set_metadata_marker",
    "strip_metadata_marker",
    "strip_portable_review_trail",
    "write_portable_review_trail",
]

from reviewkit.artifact_preservation import (
    ReviewArtifactPreservationError,
    assert_docx_structure_preserved,
)
from reviewkit.artifact_purity import ReviewArtifactPurityAssessment, assess_review_artifact_purity
from reviewkit.comment_remarks import (
    RemarkDisposition,
    RemarkWeight,
    ReviewRemark,
    compare_review_remarks,
    remark_disposition,
    remark_weight,
    review_remarks,
)

from .portable_trail import (
    PortableReviewTrailError,
    PortableReviewTrailProfile,
    append_portable_review_trail,
    has_portable_review_trail,
    strip_portable_review_trail,
    write_portable_review_trail,
)
